name: Artifact demo

on: push
    

jobs:
  job-1:
    name: Upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: "Create a local file"
        run: echo "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique eos atque deleniti! Fugiat ad voluptatum quis mollitia facere ea nostrum nam, veniam magnam illo, fugit nisi dignissimos dolorum, aspernatur excepturi?" > file.txt
      
      - uses: actions/upload-artifact@v4
        with:
          name: file
          path: file.txt
          retention-days: 14

  job-2:
    name: Download artifact
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: file
      - run: cat file.txt