name: Github Action Demo

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: env
    
  build-api:
    runs-on: windows-latest
    needs: build
    steps:
    - run: env